footprint: [[0.12, 0.125], [0.12, -0.125], [-0.12, -0.125], [-0.12, 0.125]]
footprint_padding: 0.05
# robot_radius: 0.08

# Change map topic
map_topic: /rtabmap/grid_map
# map_topic: /map

# http://wiki.ros.org/costmap_2d/hydro/obstacles
obstacle_layer:
 enabled: true

 # Global filtering parameters
 max_obstacle_height: 0.3
 obstacle_range: 5
 raytrace_range: 5
 
 # ObstacleCostmapPlugin
 track_unknown_space: true
 footprint_clearning_enabled: true
 combination_method: 1
 
 # VoxelCostmapPlugin
 origin_z: 0.0
 z_resolution: 0.2
 z_voxels: 10
 unknown_threshold: 10
 mark_threshold: 0
 publish_voxel_map: false

 # Sensor management parameters
observation_sources: laser_scan_sensor 
laser_scan_sensor: {sensor_frame: steer_bot/velodyne2, data_type: LaserScan, topic: /steer_bot/scan, marking: true, clearing: true}

# http://wiki.ros.org/costmap_2d/hydro/inflation
inflation_layer:
  enabled: true
  
  cost_scaling_factor:  4.0 
  inflation_radius:     0.45