# http://wiki.ros.org/costmap_2d

local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 3.0
  publish_frequency: 2.0
  rolling_window: true
  width: 2
  height: 2
  resolution: 0.02
  transform_tolerance: 1
  # static_map: false
  
  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}