# http://wiki.ros.org/move_base

controller_frequency: 5.0
planner_frequency: 5.0
planner_patience: 5.0
controller_patience: 5.0
conservative_reset_dist: 0.10
recovery_behavior_enabled: true
clearing_rotation_allowed: true
shutdown_costmaps: false
oscillation_timeout: 0
oscillation_distance: 0.05
max_planning_retries: -1

recovery_behaviors:
  - {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
  - {name: aggressive_reset1, type: clear_costmap_recovery/ClearCostmapRecovery}
  - {name: rotate1, type: rotate_recovery/RotateRecovery}
  - {name: aggressive_reset2, type: clear_costmap_recovery/ClearCostmapRecovery}
  - {name: rotate2, type: rotate_recovery/RotateRecovery}

conservative_reset:
  reset_distance: 0.10
  invert_area_to_clear: true
  layer_names: ["obstacle_layer"]

aggressive_reset1:
  reset_distance: 0.05
  layer_names: ["obstacle_layer"]

aggressive_reset2:
  reset_distance: 0.0 # clear all
  layer_names: ["obstacle_layer"]